
name: API test run

on:
 push:
 pull_request:

jobs:
  api-tests:
   runs-on: ubuntu-latest
   
   steps:
    - name: Check Out Repo
      uses: actions/checkout@v4
      
    - name: Set up Node
      uses:  actions/setup-node@v6
      with:
       node-version: '20'
       
    - name: Install Newman
      run: npm install -g newman
      
    - name: Run API tests
      run: newman run "Trello API.postman_collection.json" --env-var "trellokey=${{ secrets.TRELLO_KEY }}" --env-var "trelloToken=${{ secrets.TRELLO_TOKEN }}" -r cli,junit --reporter-junit-export results.xml
      
    - name: upload report
      uses: actions/upload-artifact@v4
      with:
       name: newman-report--${{ github.run_number }}
       path: results.xml
